### ISSUE TITLE
OpenWrt-x86 2023-03-06 09:49:09  qemu运行错误

### ISSUE THREAD

**Issue by wordscode** [yunxi993/OpenWrt-ARMv8#12]
Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000004
[    5.112207] Kernel Offset: disabled
[    5.112207] Rebooting in 1 seconds..

用的openwrt-x86-64-generic-squashfs-combined-efi.img.gz
但是我刷原生的x86就可以

**Comment by yunxi993** [comment]
一会儿更新下配置，你这日志太少了、联系不到上下文.
