### ISSUE TITLE
真心求助希望得到你的帮助

### ISSUE THREAD

**Issue by 2286927** [yunxi993/OpenWrt-ARMv8#3]
其实我已经反复刻了折腾了你这个仓库好久了估计有两个星期了吧，还是不会处理弄不明白，所以不得以在这向你请求帮助。我只是想在你的这个仓库基础上加入自己常用的AdguardHome和ZeroTier One，用来在我的章鱼星球上自己使用。我遇到的问题在下面这个步奏就不会处理了，真心希望得到你的帮助。
Upload OpenWrt Firmware to Release
Error 403: Resource not accessible by integration

**Comment by yunxi993** [comment]
你把你的库发给我，我去看看

**Comment by 2286927** [comment]
> 
你能得到你帮助太感谢了，我的链接如下，默认状态下你能看了吗？我怎么把仓库权限开放给你呢？
https://github.com/2286927/OpenWrt-ARMv8

**Comment by 2286927** [comment]
> 你把你的库发给我，我去看看

你能得到你帮助太感谢了，我的链接如下，默认状态下你能看了吗？我怎么把仓库权限开放给你呢？
https://github.com/2286927/OpenWrt-ARMv8

**Comment by yunxi993** [comment]
> > 你把你的库发给我，我去看看
> > 我反复修改后为一个一个排除问题，目前就直接复刻了没做修改
> > 你能得到你帮助太感谢了，我的链接如下，默认状态下你能看了吗？我怎么把仓库权限开放给你呢？
> > https://github.com/2286927/OpenWrt-ARMv8

你编译成功了在上传到Releases出了问题.
你github是不是没开token

**Comment by 2286927** [comment]
> > > 你把你的库发给我，我去看看
> > > 我反复修改后为一个一个排除问题，目前就直接复刻了没做修改
> > > 你能得到你帮助太感谢了，我的链接如下，默认状态下你能看了吗？我怎么把仓库权限开放给你呢？
> > > https://github.com/2286927/OpenWrt-ARMv8
> 
> 你编译成功了在上传到Releases出了问题. 你github是不是没开token

可能是，我去开发者设置里开了个人令牌，但开了不知道怎么用在这个仓库上。所以还是得向你学习在哪开token😅

**Comment by 2286927** [comment]
> > > > 你把你的库发给我，我去看看
> > > > 我反复修改后为一个一个排除问题，目前就直接复刻了没做修改
> > > > 你能得到你帮助太感谢了，我的链接如下，默认状态下你能看了吗？我怎么把仓库权限开放给你呢？
> > > > https://github.com/2286927/OpenWrt-ARMv8
> > 
> > 
> > 你编译成功了在上传到Releases出了问题. 你github是不是没开token
> 
> 可能是，我去开发者设置里开了个人令牌，但开了不知道怎么用在这个仓库上，不知道是不是这样开token。所以还是得向你学习怎么开token😅

**Comment by yunxi993** [comment]
> > 
> > 可能是，我去开发者设置里开了个人令牌，但开了不知道怎么用在这个仓库上，不知道是不是这样开token。所以还是得向你学习怎么开token😅

首先创建一个token,然后 Settings - Secrets - actions创建，名称 ACTIONS_TRIGGER_PAT
Value填你获得的token，token要保存好，不要泄漏了.

**Comment by 2286927** [comment]
> 

能得到你的解答我心里非常高兴，心情棒极致了！感谢你解答了多日不解的疑惑，谢谢你🙏。祝愿你身体健康，笑口常开😁

**Comment by yunxi993** [comment]
> > 
> 
> 能得到你的解答我心里非常高兴，心情棒极致了！感谢你解答了多日不解的疑惑，谢谢你🙏。祝愿你身体健康，笑口常开😁

小事，不用谢！
