### ISSUE TITLE
我又来求助了，我遇见Error: Error 403: Resource not accessible by integration问题不知道怎么处理

### ISSUE THREAD

**Issue by 2286927** [yunxi993/OpenWrt-ARMv8#4]
OpenWrt_ARMv8.config这个文件直接复刻你的并不做改变，就遇见Error: Error 403: Resource not accessible by integration这个问题；
OpenWrt_Selfuse.config这个我删除了一些不用的行和添加zerotier、在添加Adguardhome时进去就会出现编译不成“WARNING: Makefile 'package/feeds/kenzo/luci-app-adguardhome/Makefile' has a dependency on 'adguardhome', which does not exist”，然后我就rm -f把luci-app-adguardhome删了。
仓库里至今成一个固件，到现在还是在用你这个里的（苦笑）
我的仓库地址https://github.com/2286927/OpenWrt-ARMv8/actions

**Comment by yunxi993** [comment]
你把你现在fork我的仓库删掉，重新fork，然后添加好token，你给我说你想添加什么东西？
你添加的luci，你是直接在github修改的，还是创建虚拟机，在虚拟机上面修改后然后在github修改的.

**Comment by 2286927** [comment]
> 你把你现在fork我的仓库删掉，重新fork，然后添加好token，你给我说你想添加什么东西？ 你添加的luci，你是直接在github修改的，还是创建虚拟机，在虚拟机上面修改后然后在github修改的.

嗯嗯，很高兴你对我的再次耐心帮助，我是直接在Github上修改config文件的。我中午有空再照你说的做试试

**Comment by yunxi993** [comment]
> 谢谢你，在你的耐心帮助下我终于通过你的仓库编译上了我自己需要的固件，在这个过程令我体会到了学习有所收获的奇妙体验，谢谢你～愿您身体健康生活愉快！

不用谢!!！
