### ISSUE TITLE
我突然发现一个不是问题的问题

### ISSUE THREAD

**Issue by lzqd** [yunxi993/OpenWrt-ARMv8#9]
我突然发现一个不是问题的问题
能不能调整一下默认的请求 DHCP 时发送的主机名，不注意就是qnmlgb，是不是有点不太合适？

**Comment by yunxi993** [comment]
> 我突然发现一个不是问题的问题 能不能调整一下默认的请求 DHCP 时发送的主机名，不注意就是qnmlgb，是不是有点不太合适？

这个名称是有理由的，可能你没有遇到过，部分地区如果使用默认名称会有重连的情况出现，改成类似 qnmlgb 这样的名称，不会出现重连等情况.（经过一些网友实验得出的结论）

**Comment by lzqd** [comment]
> > 我突然发现一个不是问题的问题 能不能调整一下默认的请求 DHCP 时发送的主机名，不注意就是qnmlgb，是不是有点不太合适？
> 
> 这个名称是有理由的，可能你没有遇到过，部分地区如果使用默认名称会有重连的情况出现，改成类似 qnmlgb 这样的名称，不会出现重连等情况.（经过一些网友实验得出的结论）

这个名字会不会有点太内涵了？

**Comment by yunxi993** [comment]
> 这个名字会不会有点太内涵了？

你可以自己手动改一下
不清楚你的设备
或者Fork仓库，改成如下名称就会变成 OpenWrt
```
# Hostname
# sed -i 's/OpenWrt/qnmlgb/g' package/base-files/files/bin/config_generate
